### ISSUE TITLE
StartExperimentSFCEdge can not find energy-physical.json_5_MFF_log.out.txt 

### ISSUE THREAD

**Issue by fatemehm** [Cloudslab/cloudsimsdn#12]
Hi
when I try to run the StartExperimentSFCEdge and StartExperimentSFC codes "this file not found the error" occurs:

Exception in thread "main" java.io.FileNotFoundException: ./SFC_Off_dataset-energy/energy-physical.json_5_MFF_log.out.txt (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.main(StartExperimentSFCEdge.java:189)

Would you please tell me how can figure out this problem. This is an emergency for me :(
Best regards,

**Comment by hetianzhang** [comment]
Hi @fatemehm,

For the StartExperimentSFCEdge, the configuration is like this:

LFF 0 example-edge/edge.physical.json example-edge/edge.virtual.json example-edge/ edge.workload_host1.csv edge.workload_host2.csv

Plus, I just fixed the bugs in CloudSim 4.0, you could download the src code and build the project yourself.

Best regards
