### ISSUE TITLE
Example run error

### ISSUE THREAD

**Issue by Biyi-lab** [Cloudslab/cloudsimsdn#15]
Hi
when I try to run the StartExperimentSFCEdge and SimpleExampleInterCloud codes, some error occurs:
The run configuration is set according to the tutorial.

SimpleExampleInterCloud:
`java.lang.NullPointerException
	at org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud.getAllHostList(SimpleExampleInterCloud.java:212)
	at org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud.startSimulation(SimpleExampleInterCloud.java:192)
	at org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud.main(SimpleExampleInterCloud.java:168)
Unwanted errors happen`

StartExperimentSFCEdge:
`java.lang.Exception: net : Error - this entity has no PEs. Therefore, can't process any Cloudlets.
	at org.cloudbus.cloudsim.Datacenter.<init>(Datacenter.java:104)
	at org.cloudbus.cloudsim.sdn.physicalcomponents.SDNDatacenter.<init>(SDNDatacenter.java:61)
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.createSDNDatacenter(StartExperimentSFCEdge.java:441)
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.createPhysicalTopology(StartExperimentSFCEdge.java:377)
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.main(StartExperimentSFCEdge.java:291)`

`java.lang.NullPointerException
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.getAllHostList(StartExperimentSFCEdge.java:360)
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.startSimulation(StartExperimentSFCEdge.java:340)
	at org.cloudbus.cloudsim.sdn.example.StartExperimentSFCEdge.main(StartExperimentSFCEdge.java:316)`

Any helpful answer will be appreciated! Thank you!

**Comment by magaboomchen** [comment]
Hi! I meet this problem too.
Could you please tell me how to solve this problem?

**Comment by magaboomchen** [comment]
Hi! I meet this problem too.
Could you please tell me how to solve this problem?
@BEsdn
